### ISSUE TITLE
Routes return error: TypeError: Cannot read property 'forEach' of undefined

### ISSUE THREAD

**Issue by mmahalwy** [davezuko/jshint-loader-stylish#1]
This happens for all my route, not sure why specifically only those....

```
./src/scripts/components/Application.js
Module build failed: TypeError: Cannot read property 'forEach' of undefined
    at forEach (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader-stylish/node_modules/text-table/index.js:73:11)
    at /Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader-stylish/node_modules/text-table/index.js:10:9
    at Array.reduce (native)
    at reduce (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader-stylish/node_modules/text-table/index.js:63:30)
    at module.exports (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader-stylish/node_modules/text-table/index.js:9:20)
    at Object.<anonymous> (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader-stylish/reporters/true-stylish.js:30:17)
    at Object.jsHint (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader/index.js:110:13)
    at Object.<anonymous> (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader/index.js:146:11)
    at Object.<anonymous> (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader/index.js:37:12)
    at respond (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader/node_modules/rcloader/index.js:68:7)
    at respond (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader/node_modules/rcloader/node_modules/rcfinder/index.js:140:7)
    at next (/Users/mmahalwy/Desktop/Code/quran.com/frontend/node_modules/jshint-loader/node_modules/rcloader/node_modules/rcfinder/index.js:167:16)
    at process._tickCallback (node.js:355:11)
 @ ./app.js 13:29-62
```

**Comment by dvdzkwsk** [comment]
Hey, could you provide a code snippet that's causing the issue? I haven't really been working on this package too much, but I can take a look and see what can be done.

**Comment by mmahalwy** [comment]
Hey no worries. I actually moved to eslint
